### ISSUE TITLE
Filter page enhancement

### ISSUE THREAD

**Issue by cd11103** [ViviGroupe/vivicrew-web#33] opened 2017-06-14 10:37 UTC
![2 1](https://user-images.githubusercontent.com/13926253/27128282-7b450bb0-5130-11e7-8e9b-3f8634ba0716.PNG)

**Comment by kevinlaw91** [comment] 2017-06-14 14:13
Closed as duplicate of #35

**Closed by kevinlaw91** 2017-06-14 14:13 UTC
